# Generated by Django 4.2.7 on 2023-11-16 15:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('image_api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='image',
            old_name='description',
            new_name='Department',
        ),
    ]
