# Generated by Django 4.2.7 on 2023-11-16 15:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('image_api', '0002_rename_description_image_department'),
    ]

    operations = [
        migrations.RenameField(
            model_name='image',
            old_name='Department',
            new_name='department',
        ),
    ]
