# Generated by Django 4.2.7 on 2023-11-16 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('image_api', '0003_rename_department_image_department'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='love_most',
            field=models.TextField(),
        ),
    ]
